import {console, hex, bold, link} from './console.js';
const ms = Date.now();
const tab = hex('#767676')('- ');
const commits = await fetch('https://api.github.com/repos/koloja/koloja.dev/commits');
const repos = await fetch('https://api.github.com/users/koloja/repos');
const reposJSON = await repos.json();
const languageStats = reposJSON.reduce((acc, repo) => {
    if (repo.language) acc[repo.language] = (acc[repo.language] || 0) + 1;
    return acc;
}, {});
const totalRepos = repos.length;
const commitsJSON = await commits.json();
const commit = commitsJSON[0].sha.substring(0, 7);

console.log(`${hex('#69ca7a')(bold('KOLOJA'))} ${hex('#767676')(`${commit}, ${Date.now() - ms}ms`)}`);
console.log('\n');
console.log('I code stuff,  I think.');
console.log(`Im ${hex('#f2f2f2')('koloja')}, currently apart of ${hex('#50c675')(link('https://znci.dev/', 'ZNCI'))} as a ${hex('#f2f2f2')('junior developer')}.`);
console.log(`I specialize in ${hex('#f2f2f2')('web development')} with fullstack tools like ${hex('#f2f2f2')(link('https://vitejs.dev/', 'ViteJS'))} and ${hex('#f2f2f2')(link('https://expressjs.com/', 'ExpressJS'))}.`);
console.log('\n');
console.log('\n');
console.log(hex('#3a96dd')(bold('SKILLS')));
console.log('What skills do I have?');
console.log('\n');
console.log(`${tab}${hex('#e8d44d')('JAVASCRIPT')} ${hex('#767676')(`Experienced`)}`);
console.log(`${tab}${hex('#2f74c0')('TYPESCRIPT')} ${hex('#767676')(`Experienced`)}`);
console.log(`${tab}${hex('#f79300')('SKRIPT-LANG')} ${hex('#767676')(`Experienced (If it means anything)`)}`);
console.log(`${tab}${hex('#dd4b25')('HTML')} ${hex('#767676')(`Experienced`)}`);
console.log(`${tab}${hex('#3595cf')('CSS')} ${hex('#767676')(`Experienced`)}`);
console.log(`${tab}${hex('#509941')('NodeJS')} ${hex('#767676')(`Experienced`)}`);
console.log(`${tab}${hex('#f7f7f7')('ExpressJS')} ${hex('#767676')(`Experienced`)}`);
console.log(`${tab}${hex('#5ed3f3')('ReactJS')} ${hex('#767676')(`Intermediate`)}`);
console.log(`${tab}${hex('#b42ff1')('ViteJS')} ${hex('#767676')(`Intermediate`)}`);
console.log(`${tab}${hex('#e99921')('JAVA')} ${hex('#767676')(`Basic`)}`);
console.log(`${tab}${hex('#6195cb')('C')} ${hex('#767676')(`Learning`)}`);
console.log(`${tab}${hex('#4588b9')('GD-SCRIPT')} ${hex('#767676')(`Learning`)}`);
console.log(`${tab}${hex('#95181b')('WEBGL')} ${hex('#767676')(`Learning`)}`);
console.log(`${tab}${hex('#fd6f42')('RUST')} ${hex('#767676')(`Learning`)}`);
console.log('\n');
console.log('\n');
console.log(hex('#ff28df')(bold('LINKS')));
console.log(`Some usefull links you might want or need.`);
console.log('\n');
console.log(`${tab}${hex('#ff4646')(link('https://youtube.com/@koloja', 'YOUTUBE'))} ${hex('#767676')(`Dont post on it but whatever`)}`);
console.log(`${tab}${hex('#f7f7f7')(link('https://github.com/koloja', 'GITHUB'))} ${hex('#767676')(`Check out the code for this epic website`)}`);
console.log(`${tab}${hex('#5562ea')(link('https://discord.com/users/441683482800816138', 'DISCORD'))} ${hex('#767676')(`Contact me IG?`)}`);
